### ISSUE TITLE
append() causes a slice to be modified when it shouldn't

### ISSUE THREAD

**Issue by dradtke** [gopherjs/gopherjs#574]
I came across this bug by playing around with [vdom](https://github.com/albrow/vdom). I initially opened https://github.com/albrow/vdom/pull/2, but that contains two bugs: one is a bug in the `vdom` package itself and is a very simple fix, and the other is an issue that appears to be caused by GopherJS' implementation of append().

The `vdom` package works by maintaining "index paths" for each DOM node as it walks the children of your chosen root. Each path is an int slice representing successive lookups; for example, the slice `[]int{1, 3, 2}` would roughly translate to `root.childNodes[1].childNodes[3].childNodes[2]`. While attempting to create a simple React-like edit grid using `vdom`, I ran into a `HierarchyRequestError` on rerender, and further investigation caused me to discover that an index value was being modified _after_ it had already been parsed and saved in the virtual tree, meaning it pointed to a part of the DOM that didn't support the requested operation. More specifically, a call to append() on the index slice of an unrelated node was also modifying a slice that it shouldn't have been.

A demonstration of the issue can be found [here](https://github.com/dradtke/gopherjs-bug-demo); simply clone that repo somewhere and run it to see the `HierarchyRequestError` in action. The `index.html` file can be updated to the working version of the script to see the issue resolved. As noted in the comments at the top of each javascript file in that repo, they were generated using different implementations of `vdom`, with this being the difference between the broken version and the working version:

```diff
diff --git a/parse.go b/parse.go
index 638acdd..7b83614 100644
--- a/parse.go
+++ b/parse.go
@@ -59,7 +59,7 @@ func parseToken(tree *Tree, token xml.Token, currentParent *Element) (nextParent
                }
                if currentParent != nil {
                        // Set the index based on how many children we've seen so far
-                       el.index = append(currentParent.index, len(currentParent.children))
+                       el.index = intAppend(currentParent.index, len(currentParent.children))
                        // Set this element's parent
                        el.parent = currentParent
                        // Add this element to the currentParent's children
@@ -131,7 +131,7 @@ func parseToken(tree *Tree, token xml.Token, currentParent *Element) (nextParent
                }
                if currentParent != nil {
                        // Set the index based on how many children we've seen so far
-                       text.index = append(currentParent.index, len(currentParent.children))
+                       text.index = intAppend(currentParent.index, len(currentParent.children))
                        // Set this text node's parent
                        text.parent = currentParent
                        // Add this text node to the currentParent's children
@@ -152,7 +152,7 @@ func parseToken(tree *Tree, token xml.Token, currentParent *Element) (nextParent
                }
                if currentParent != nil {
                        // Set the index based on how many children we've seen so far
-                       comment.index = append(currentParent.index, len(currentParent.children))
+                       comment.index = intAppend(currentParent.index, len(currentParent.children))
                        // Set this comment node's parent
                        comment.parent = currentParent
                        // Add this comment node to the currentParent's children
@@ -205,3 +205,12 @@ func wasAutoClosed(tree *Tree, tagName string) bool {
        // were not the closing tag.
        return string(tree.reader.buf[start:stop]) != closingTag
 }
+
+// intAppend() is a redefinition of append() that explicitly creates
+// a new copy of the slice and copies the elements into it.
+func intAppend(slice []int, elems ...int) []int {
+       s := make([]int, len(slice)+len(elems))
+       copy(s, slice)
+       copy(s[len(slice):], elems)
+       return s
+}
```

The intAppend() method, theoretically, does exactly what append() does when operating on an int slice, minus some optimizations using capacity. However, for some reason, the example page works with intAppend(), but not append(). Unfortunately, I don't know enough about GopherJS' implementation to explain why, but hopefully that will give someone enough information to figure out the root cause.

**Comment by shurcooL** [comment]
As I posted in https://github.com/albrow/vdom/pull/2#issuecomment-271777220:

> I've tried some basics like http://www.gopherjs.org/playground/#/B3z9BQtHDu, and couldn't spot any differences in behavior (aside from capacity increase being different, but that doesn't seem to be a violation of Go spec).

So this will require some further digging.

One thing to note is that you're `intAppend` never modifies the original slice, even when there's sufficient capacity to reuse the backing array. This means it's _possible_ that it's the user code that requires that behavior, and not a bug in `append` behavior. Of course, it might also be a bug, I just wanted to point out this alternative explanation.

**Comment by dradtke** [comment]
I pushed a custom branch to the `vdom` repo that adds some logging statements specific to this issue that may be able to shed some light.

[demo](https://github.com/dradtke/gopherjs-bug-demo) | [vdom branch](https://github.com/dradtke/vdom/tree/append-bug-demo)

To see the issue:

1. Clone that custom `vdom` branch and install it to `github.com/albrow/vdom`
2. Clone the demo
3. Build the demo's script via `gopherjs build script.go`
4. Modify the demo's `index.html` to load `script.js`

On my computer, here's the output that I see:

```
Node index was modified from [1 1 1 3] to [1 1 1 4]!
  problemChild =  &{td [] 0x1 [0x1] 0x1 55 86 59 81 false [1 1 1 4]}
  text =  &{[10 32 32 32 32] <nil> [1 1 1 4]}
  currentParent =  &{tr [] 0x1 [0x1 0x1 0x1 0x1] 0x1 23 0 27 0 false [1 1 1]}
  currentParent.index =  [1 1 1]
  len(currentParent.children) =  4
```

What's happening here is that the second `<td>` node (normally indexed by `[1, 1, 1, 3]` and referred to as `problemChild`) is having its last element incremented on a `CharEvent` underneath the `<tr>` node.

The line of code that causes the issue is this:

```go
text.index = append(currentParent.index, len(currentParent.children))
```

Note that this line only references `currentParent` and `text`, but `problemChild`'s index is also somehow being modified. This shouldn't even be modifying `currentParent`; it's only supposed to be setting the index of `text` (which it does do successfully).

Hopefully that helps the issue become a little more clear.

**Comment by neelance** [comment]
I really need a short test case here. Please trim it down to a test case of max 20 lines which shows wrong behavior. Right now I'm still missing the proof that this is actually a bug in GopherJS.

Are you aware of the following behavior of Go? Maybe that is what you're running into.
```
package main

import "fmt"

func main() {
	a := []int{1, 2, 3}
	b := a[:2]
	c := append(b, 4)
	d := append(b, 5)
	fmt.Println("a", a) // a [1 2 5], NOT [1 2 3]
	fmt.Println("b", b) // b [1 2]
	fmt.Println("c", c) // c [1 2 5], NOT [1 2 4]
	fmt.Println("d", d) // d [1 2 5]
}
```
Try here: https://play.golang.org/p/dOts34XAcz

**Comment by dradtke** [comment]
Ah, after further investigation, I've come to the conclusion that it most likely is not a bug in GopherJS' implementation of `append()`. I managed to more or less reproduce the issue in a primarily Go context, and the root cause appears to be some unexpected backing-array sharing.

Apologies for the noise, and thanks for helping me narrow this down.
